Loopring/loopr

src/datas/config.json
src/market/operation-panel.html

add white list check before submit order

white list check

---

src/page-doc.html

loopr-doc redirect to 404 when not found

loopr-doc redirect to 404 when not found

---

src/history/subpage-orders.html
src/history/subpage-trades.html
src/market/operation-panel.html
src/market/order-table.html
src/market/trade-table.html
src/my-app.html
src/page-approve.html
src/page-convert.html
src/page-doc.html
src/page-history.html
src/page-market.html
src/page-order.html
src/page-ring.html
src/page-transfer.html
src/page-wallet.html
src/unlocked-wallet/wallet-assets.html
src/unlocked-wallet/wallet-orders.html
src/unlocked-wallet/wallet-trades.html
src/wallet/subpage-ready.html

1. my-app add balances ajax loading(add into global variable), remove old loadings in other pages
2. sub-pages accept attributes: page, subpage, third..., in sub-page compute  parameters(market, token...)

balance loading & sub-page attributes

---

src/external-lib-imports.html
src/my-app.html

adjust to loopring.js rename priavateKey to Wallet

 rename priavateKey to Wallet

---

src/loopr-page/simple-toolbar.html
src/market/operation-panel.html
src/market/order-table.html
src/market/trade-table.html
src/page-market.html

1. bug fix: Operation Panel balance calculate error when token has no balance.
2. When no market found, show notification bar when redirect to 404
3. bug fix: simple-toolbar.html id changed not recalculate title

fix some bug in operation-panel and simple-toolbar

---

src/market/order-table.html
src/page-approve.html
src/page-convert.html
src/page-transfer.html

fix bugs in generate Extra Data

fix generate Extra Data

---

src/external-lib-imports.html
src/my-app.html
src/page-approve.html
src/page-convert.html
src/page-transfer.html

Datause signer to gengerate ETH tx extra data,and remove ethereumjs-util

adapt to latest loopring.js to generate ETH Tx extra data

---

bower.json
src/market/candlestick-chart.html
src/market/depth-chart.html
src/my-app.html
src/page-convert.html
src/page-order.html
src/page-transfer.html
src/unlocked-wallet/wallet-assets.html
src/unlocked-wallet/wallet-orders.html
src/utils/cutoff-panel.html

fix get current Version Contract Address bug, and complete set cut off

complete set cut off

---

src/history/subpage-orders.html
src/history/subpage-trades.html
src/market/trade-table.html
src/page-history.html
src/unlocked-wallet/wallet-assets.html

fix a bug when not found token config

bugfix when not found token config

---

src/app-config-mixin.js
src/page-approve.html
src/page-convert.html
src/page-transfer.html
src/utils/pretty-number.html

1.  If address has no balance display 0
2. approve, convert, transfer page return to wallet when not found token

Approve, Convert, Transfer page return to wallet when not found token

---

src/history/subpage-rings.html
src/loopr-page/ethereum-signer.html
src/loopr-page/signtosend-dialog.html
src/market/operation-panel.html
src/market/order-table.html
src/market/trade-table.html
src/my-app.html
src/page-approve.html
src/page-convert.html
src/page-markets.html
src/page-settings.html
src/page-transfer.html
src/utils/cutoff-panel.html
src/utils/market-search.html
src/utils/market-tab.html

1、cookie values set to global values
2、get values on other pages by global values

global values bug fix

---

src/loopr-page/order-dialog.html
src/market/operation-panel.html
src/my-app.html
src/page-approve.html

1、new method of place order
2、 adjust operation panel

redo place order

---

src/market/operation-panel.html

change order lrc fee

---

src/page-404.html

add a better 404 page

---

src/my-app.html
src/page-history.html
src/page-wallet.html
src/unlocked-wallet/wallet-assets.html
src/utils/asset-search.html
src/wallet/subpage-ready.html

1. bugfix: page.go may be loaded many times
2. datas in "wallet" and "history" subpages will be loaded everytime and only once when tab changes

bugfix: page.go may be loaded many times

---

src/loopr-page/order-dialog.html
src/market/operation-panel.html

1、 compare lrcBalance and lrcAllowance with lrcFee when place an order
2、add authorizations when lrcAllowanc is not enough to pay lrc Fee while lrc Balance is enough.

fix lrc fee when place an order

---

src/market/operation-panel.html
src/utils/loopr-relay-ajax.html

maker salt and jsonrpc id smaller

fix salt and jsonrpc id

---

bower.json
src/external-lib-imports.html
src/my-app.html

1、 use loopring.min.js instead

checkloopringjs

---

src/page-approve.html

 fix approve

---

bower.json
src/loopr-page/order-dialog.html
src/loopr-page/signtosend-dialog.html

fix send txs

---

src/page-approve.html

1、fix approve amount and approve tx

fix approve page

---

src/loopr-page/order-dialog.html
src/loopr-page/signtosend-dialog.html
src/market/operation-panel.html
src/page-approve.html

1、fix delegate address
2、fix palce order  lrc fee and margin split 
3、fix tx send

fix approve and send tx

---

.gitignore
src/app-config-mixin.js
src/market/trade-table.html
src/my-app.html
src/page-approve.html
src/page-convert.html
src/page-doc.html
src/page-history.html
src/page-market.html
src/page-order.html
src/page-ring.html
src/page-settings.html
src/page-transfer.html
src/page-wallet.html
src/unlocked-wallet/wallet-assets.html
src/unlocked-wallet/wallet-orders.html
src/unlocked-wallet/wallet-trades.html
src/utils/cutoff-panel.html
src/utils/loopr-ajax.html
src/utils/loopr-relay-ajax.html
src/wallet/subpage-ready.html

1. use checkbox to display "hide 0 banlance"
2. add convert, approve, transfer pages  redirect to unlock check
3. change {page, subpage, third} properties to original route
4. asset tokens display sorted by name

Use checkbox to display "hide 0 banlance" and some bug fix

---

src/loopr-page/order-dialog.html
src/loopr-page/signtosend-dialog.html

1、 fix bugs when send more than one transaction at the same time

fix send tx

---

src/loopr-page/order-dialog.html
src/loopr-page/signtosend-dialog.html

fix dialog

---

src/history/subpage-rings.html
src/market/candlestick-chart.html
src/market/trade-table.html
src/my-app.html
src/page-markets.html
src/page-order.html
src/page-settings.html
src/unlocked-wallet/wallet-assets.html
src/utils/loopr-ajax.html
src/utils/loopr-relay-ajax.html

1. add favorite in Markets and Assets
2. fix bug: notification bar display error relay name

Add favorite in Markets and Assets

---

package.json
src/external-lib-imports.html
src/market/operation-panel.html

1、 take history order amount into consideration  when compute approve amount

fix place order

---

src/loopr-page/order-dialog.html
src/loopr-page/signtosend-dialog.html
src/market/operation-panel.html
src/my-app.html
src/page-approve.html

1、test and fix bugs on mainNet

Yd changetomain net

---

src/page-ring.html
src/utils/notification-panel.html

add target=_blank

---

src/market/order-book.html
src/page-markets.html

market change

---

src/market/operation-panel.html
src/my-app.html
src/page-settings.html
src/utils/cutoff-panel.html

1. add expire time setting
2. use current timestamp to commit cutoff
3. modify approve value when place a order

WIP: add expire time setting

---

src/market/operation-panel.html

1、convert ETH to WETH when palce order when WETh is not enogh.

add convert when place order

---

src/loopr-page/txamountconfirm-dialog.html
src/market/operation-panel.html
src/page-approve.html
src/page-convert.html
src/page-market.html
src/page-transfer.html

1、add relay market filter
2、fix converter and transfer bugs
3、fix bignumber

Yd support market
